### ISSUE TITLE
Render text

### ISSUE THREAD

**Issue by orta** [jest-community/jest-snapshots-svg#11]
> ## Custom measurements
> Certain nodes need to ability to measure themselves, the most common example is nodes which represent text. Text has an intrinsic size and requires measuring itself to determine that size. This is not something Yoga can do as it requires relying on the host system’s text rendering engine.

https://facebook.github.io/yoga/docs/api/javascript/#custom-measurements

-- 

So in order to get any semblance of layouts, we have to do some kind of text rendering

This is tricky as a node could rely on the height of another node before being set.

**Comment by orta** [comment]
Can fake it for now by setting the height to be the font size * 2 for a simple stub

**Comment by orta** [comment]
#12 does. ^

**Comment by orta** [comment]
I did the stub for now #16 does it correctly

When I experimented with multi-line text in sketch, it looked like this

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="63px" height="23px" viewBox="0 0 63 23" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="11" font-family="AvantGardeGothicITCW01Dm, Avant Garde Gothic ITCW01Dm" letter-spacing="0.730000019" font-weight="normal">
        <text id="Here-is-some-text" fill="#5A2A2A">
            <tspan x="9.98349993" y="8">Here is </tspan>
            <tspan x="0.414999914" y="22">some text</tspan>
        </text>
    </g>
</svg>
```

which means we'll have to handle per-line text rendering in the client. Worth taking a look at how React Native does this, as it must pass it to cocoa somehow.

**Comment by orta** [comment]
It's worth can experimenting with https://github.com/manaflair/text-layout

**Comment by orta** [comment]
there is a textArea SVG attribute which may drastically simplify this

**Comment by orta** [comment]
the `textArea` SVG attribute was removed -  https://www.w3.org/Graphics/SVG/WG/wiki/SVG2_Requirements_Input#the_textArea_element

**Comment by orta** [comment]
But, it turns out this super-crazy hack by injecting HTML works in the preview: https://github.com/orta/jest-snapshots-svg/blob/text_blocks/src/_tests/example_layouts/__snapshots__/_text.test.tsx-renders-text-blocks.svg

**Comment by jacobp100** [comment]
Can we use something like [txtjs](http://txtjs.com) to format the words onto lines, and then use plain old tspans?

**Comment by orta** [comment]
I'd happily switch if that works, the current hack is indeed crazy

**Comment by jaredly** [comment]
Looks like this is done? https://github.com/jest-community/jest-snapshots-svg/commit/31ddd686f947e986da4840c0e6ba83cbba2a25ab

**Comment by orta** [comment]
Yep - thanks, closing
