### ISSUE TITLE
Use color of text for background color for text nodes

### ISSUE THREAD

**Issue by orta** [jest-community/jest-snapshots-svg#25]
While #11 isn't happening, making a preview of this

<img width="459" alt="screen shot 2017-06-14 at 13 54 04" src="https://user-images.githubusercontent.com/49038/27133089-efd28476-5108-11e7-9edd-729eaf193a71.png">

is completely black :D

**Comment by jacobp100** [comment]
Is this still an issue?

**Comment by orta** [comment]
I'd bet probably not now
