### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by jacobp100** [jest-community/jest-snapshots-svg#36]
Do we have handling for borders? I’d be interested to hear your thoughts! I’ll just jot a few notes I had on it:

SVG strokes are drawn both sides of the shape, whereas in RN they are drawn inside. We need to inset the x, y, width, and height by the borders on those sides.

We need to handle scaling border radii down when you have a border radius of say 1000 in a box that is 50x50. We also need to handle % border radii, which are handled differently.

If the border width and colour is consistent on all sides, we can just set the stroke on the main shape. For different border colours, we will have to use different paths. For different border widths, we may not be able to use the stroke, and may have to draw this as a filled path.

**Comment by orta** [comment]
I've not put much thought into it yet, the Artsy design style doesn't really have many bordered objects, so I've not had to think of how to represent it. 

There's also border radius, and border styles to worry about 🍡 
https://facebook.github.io/react-native/docs/viewstyleproptypes.html

**Comment by orta** [comment]
#37 handles some of this 👍
