### ISSUE TITLE
Need to be able to set default font

### ISSUE THREAD

**Issue by dawnmist** [jest-community/jest-snapshots-svg#54]
While Helvetica is one of the default fonts in MacOS, it is not usually available in Linux and only sometimes available in Windows (with Adobe products). This makes it difficult to:
* Contribute patches to jest-snapshots-svg, as text-rendering tests rely on the exact spacing of Helvetica.
* Use the library on any system that is not a Mac.

For use, it needs to be possible to specify a font to use as the default font.

For development, a universally-available (or redistributable) font needs to be used as the default font for testing so that the tests do not break on different OS's.

**Comment by orta** [comment]
Yeah, this make sense 👍 

It'd have to be distributed, because there isn't really a [universal font](http://web.mit.edu/jmorzins/www/fonts.html) installed on all devices.  We could have tests use something like https://fontlibrary.org/en/font/source-serif-pro which has a compatible license

**Comment by dawnmist** [comment]
Google have a collection of free, open source, redistributable fonts at https://fonts.google.com/

**Comment by dawnmist** [comment]
Released in 0.1.0
